server_port: ":8081"
html_root_dir: D:/ai-ws/gen8id-fo-frontend/dist #D:/ai-ws/gen8id-fo-frontend/public

og_url: https://www.gen8.id
og_site_name: Generated(gen8.id)
og_type: website
og_title: Landing page
og_description: Generated | The way to make Money using generative AI.
og_image: https://www.gen8.id/img/meta/og_image.webp
og_image_type: image/webp
og_image_width: 1200
og_image_height: 630
og_locale: en_US

title: Generated | The way to make Money using generative AI.
keywords: ai, generative, art, artwork, media, image, artist, midjourney, nijijourney, stable diffusion, chatgpt, robot, transformer, attention
author: Bitflow
copyright: Bitflow, Inc.


# WATERMARK_THUMB_PATH: resources/watermark-512x512.png
# UPLOAD_REL_PATH: temp_upload
# ORG_IMG_FILENAME: ORG-%d.png
# HASH_IMG_FILENAME: ORG-%s.png
# DST_IMG_FILENAME: TNS-%s.webp
# OBJ_STRG_ENDPNT: https://kr.object.ncloudstorage.com
# OBJ_STRG_REGION: kr-standard
# OBJ_STRG_ACC_KEY: LR9hW8gPyStOvacROGl3
# OBJ_STRG_SCRT_KEY: JZE1FXZObcu2tazxgEmQzx043XK8ZmSfv8JR1vlg
# OBJ_STRG_BUCKT: alpha.gen8.id
