# This server setting
ServerPort: ":8081"

# Opengraph metadata settings
OgUrl: "https://www.gen8.id"
OgSiteName: "Generated | WWW.GEN8.ID"
OgType: "website"
OgTitle: "[Generated] AI artists playground"
OgDescription: "The way to make money using generative AI."
OgImage: "https://a.gen8.id/img/samples/niji-8.png"
OgImageType: "image/png"
OgImageWidth: "1200"
OgImageHeight: "630"
OgLocale: "en_US"

TwitterCard: "summary_large_image"

Title: "[Generated] AI artist's playground"
Keywords: "ai, generative, art, artwork, media, image, artist, midjourney, nijijourney, stable diffusion, chatgpt, robot, transformer, attention"
Author: "Bitflow"
Copyright: "Bitflow, Inc."


# Wasabi object storage settings
ObjStrgEndpnt: https://s3.us-central-1.wasabisys.com
ObjStrgRegion:
ObjStrgAccKey: JFRFUXFA91SE5
ObjStrgScrtKey: iCOk3RzVEgUDJgt6oHY6S0
ObjStrgBcktName: dev-gen8id
ObjStrgFoldPblc: pblc/
ObjStrgFoldPrvt: prvt/

# Image filename settings
WtmkThmbPath: res/wm-512x512.png
UpldRltvPath: ./tmp_upld # /user/{userid}
OrgImgFileNm: tmp%d.png
HashImgFileNm: org%s.png
DstImgFileNm: fin%d.webp

