# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          server: '${{ secrets.FTP_HOST_GEN8ID_WEB }}'
          port: 22
          username: ${{ secrets.FTP_USER_GEN8ID_WEB }}             
          password: ${{ secrets.FTP_PW_GEN8ID_WEB }}                    
          local_path: './dist/*'
          remote_path: '/home/bitflow/www/alpha.gen8.id'
          sftp_only: true          
          sftpArgs: '-o ConnectTimeout=5'
